### ISSUE TITLE
Change reportDir to files

### ISSUE THREAD

**Issue by gustawdaniel-acaisoft** [0xIslamTaha/orchestrator-public-use-case#3]
https://sqa.stackexchange.com/questions/44324/cypress-problems-in-merging-individual-test-suite-mochawesome-reports-consiste

**Comment by 0xIslamTaha** [comment]
@gustawdaniel-acaisoft 
after a clear investigation, I can confirm that it's not a valid bug. We are using "reportDir" as an option for the `mochawsome` package, However the mentioned ticket was taking about `mockawsome-merge` package. 

The orchestrator is the one which is dealing with the `mockawseom-merge` and it's already using the `files` options.
